import { format } from "date-fns"
import { es } from "date-fns/locale"

export type SmartsheetColumn = {
  title: string
  type: "TEXT_NUMBER" | "DATE" | "DROPDOWN" | "CHECKBOX" | "CONTACT_LIST"
  width?: number
  primary?: boolean
}

export type SmartsheetExportOptions = {
  sheetName: string
  columns: SmartsheetColumn[]
  data: any[]
  includeMetadata?: boolean
  formatDates?: boolean
}

export class SmartsheetExporter {
  private static formatValue(value: any, formatDates = true): string {
    if (value === null || value === undefined || value === "") {
      return ""
    }

    if (typeof value === "number") {
      return value.toString()
    }

    if (value instanceof Date && formatDates) {
      return format(value, "dd/MM/yyyy", { locale: es })
    }

    if (typeof value === "boolean") {
      return value ? "Sí" : "No"
    }

    return String(value)
  }

  private static escapeCSVValue(value: string): string {
    if (value.includes(",") || value.includes('"') || value.includes("\n")) {
      return `"${value.replace(/"/g, '""')}"`
    }
    return value
  }

  static exportToCSV(options: SmartsheetExportOptions): void {
    const { sheetName, columns, data, includeMetadata = true, formatDates = true } = options

    let csvContent = ""

    // Add metadata for Smartsheet import
    if (includeMetadata) {
      csvContent += `# Smartsheet Export - ${sheetName}\n`
      csvContent += `# Exported on: ${format(new Date(), "dd/MM/yyyy HH:mm", { locale: es })}\n`
      csvContent += `# Generated by: INVOKE Hours Management System\n`
      csvContent += `# Total Records: ${data.length}\n`
      csvContent += `#\n`
    }

    // Add column headers
    const headers = columns.map((col) => this.escapeCSVValue(col.title))
    csvContent += headers.join(",") + "\n"

    // Add data rows
    data.forEach((row) => {
      const values = columns.map((col) => {
        const key = col.title.toLowerCase().replace(/\s+/g, "_").replace(/[^\w]/g, "")
        let value = row[key] || row[col.title] || ""

        // Handle special cases for common field mappings
        if (!value && col.title.toLowerCase().includes("fecha")) {
          value = row.date || row.fecha || row.createdAt || ""
        }
        if (!value && col.title.toLowerCase().includes("usuario")) {
          value = row.userName || row.consultorName || row.name || ""
        }
        if (!value && col.title.toLowerCase().includes("horas")) {
          value = row.hours || row.totalHours || row.horas || ""
        }

        const formattedValue = this.formatValue(value, formatDates)
        return this.escapeCSVValue(formattedValue)
      })
      csvContent += values.join(",") + "\n"
    })

    // Create and download file
    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" })
    const link = document.createElement("a")
    const url = URL.createObjectURL(blob)
    link.setAttribute("href", url)
    link.setAttribute("download", `${sheetName}_smartsheet_${format(new Date(), "yyyyMMdd_HHmm")}.csv`)
    link.style.visibility = "hidden"
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  static exportHourRegistrations(registrations: any[]): void {
    const columns: SmartsheetColumn[] = [
      { title: "ID Registro", type: "TEXT_NUMBER", primary: true },
      { title: "Fecha", type: "DATE", width: 120 },
      { title: "Consultor", type: "TEXT_NUMBER", width: 150 },
      { title: "Proyecto", type: "TEXT_NUMBER", width: 150 },
      { title: "Cliente", type: "TEXT_NUMBER", width: 120 },
      { title: "Product Manager", type: "TEXT_NUMBER", width: 130 },
      { title: "Tipo de Hora", type: "DROPDOWN", width: 120 },
      { title: "País", type: "TEXT_NUMBER", width: 100 },
      { title: "Horas", type: "TEXT_NUMBER", width: 80 },
      { title: "Descripción", type: "TEXT_NUMBER", width: 200 },
      { title: "Fecha Creación", type: "DATE", width: 130 },
    ]

    const data = registrations.map((reg) => ({
      id_registro: reg.id,
      fecha: reg.date,
      consultor: reg.consultorName,
      proyecto: reg.projectName,
      cliente: reg.clientName,
      product_manager: reg.productManagerName,
      tipo_de_hora: reg.hourTypeName,
      país: reg.countryName,
      horas: reg.hours,
      descripción: reg.description,
      fecha_creación: reg.createdAt,
    }))

    this.exportToCSV({
      sheetName: "Registros_Horas_INVOKE",
      columns,
      data,
    })
  }

  static exportUserManagement(users: any[]): void {
    const columns: SmartsheetColumn[] = [
      { title: "ID Usuario", type: "TEXT_NUMBER", primary: true },
      { title: "Nombre Completo", type: "TEXT_NUMBER", width: 150 },
      { title: "Email", type: "CONTACT_LIST", width: 180 },
      { title: "Rol", type: "DROPDOWN", width: 100 },
      { title: "Último Registro", type: "DATE", width: 130 },
      { title: "Estado", type: "DROPDOWN", width: 100 },
      { title: "Total Horas", type: "TEXT_NUMBER", width: 100 },
    ]

    const data = users.map((user) => ({
      id_usuario: user.id,
      nombre_completo: user.name,
      email: user.email,
      rol: user.role === "admin" ? "Administrador" : "Consultor",
      último_registro: user.lastHourRegistration,
      estado: "Activo",
      total_horas: user.totalHours || 0,
    }))

    this.exportToCSV({
      sheetName: "Gestión_Usuarios_INVOKE",
      columns,
      data,
    })
  }

  static exportReports(reportData: any[], reportType: string): void {
    const columns: SmartsheetColumn[] = [
      { title: "Período", type: "TEXT_NUMBER", width: 120 },
      { title: "Consultor", type: "TEXT_NUMBER", width: 150 },
      { title: "Proyecto", type: "TEXT_NUMBER", width: 150 },
      { title: "Cliente", type: "TEXT_NUMBER", width: 120 },
      { title: "Tipo Hora", type: "DROPDOWN", width: 120 },
      { title: "Total Horas", type: "TEXT_NUMBER", width: 100 },
      { title: "Promedio Diario", type: "TEXT_NUMBER", width: 120 },
      { title: "Días Activos", type: "TEXT_NUMBER", width: 100 },
    ]

    this.exportToCSV({
      sheetName: `Reporte_${reportType}_INVOKE`,
      columns,
      data: reportData,
    })
  }

  static exportParameterManagement(parameters: any[], parameterType: string): void {
    const columns: SmartsheetColumn[] = [
      { title: "ID", type: "TEXT_NUMBER", primary: true },
      { title: "Nombre", type: "TEXT_NUMBER", width: 150 },
      { title: "Tipo", type: "DROPDOWN", width: 120 },
      { title: "Estado", type: "DROPDOWN", width: 100 },
      { title: "Fecha Creación", type: "DATE", width: 130 },
      { title: "Descripción", type: "TEXT_NUMBER", width: 200 },
    ]

    const data = parameters.map((param) => ({
      id: param.id,
      nombre: param.name,
      tipo: parameterType,
      estado: param.status || "Activo",
      fecha_creación: param.createdAt || new Date().toISOString(),
      descripción: param.description || "",
    }))

    this.exportToCSV({
      sheetName: `Parámetros_${parameterType}_INVOKE`,
      columns,
      data,
    })
  }

  static exportDailyHoursMatrix(dailyMatrix: any[], userSummaries: any[]): void {
    if (dailyMatrix.length === 0 || userSummaries.length === 0) return

    // Create dynamic columns based on users
    const columns: SmartsheetColumn[] = [{ title: "Fecha", type: "DATE", primary: true, width: 120 }]

    userSummaries.forEach((user) => {
      columns.push({
        title: user.userName,
        type: "TEXT_NUMBER",
        width: 100,
      })
    })

    // Prepare data
    const data = dailyMatrix.map((day) => {
      const row: any = {
        fecha: day.formattedDate,
      }

      userSummaries.forEach((user) => {
        const key = user.userName.toLowerCase().replace(/\s+/g, "_")
        row[key] = day.userHours[user.userId] || ""
      })

      return row
    })

    // Add summary row
    const summaryRow: any = {
      fecha: "SUMA TOTAL",
    }
    userSummaries.forEach((user) => {
      const key = user.userName.toLowerCase().replace(/\s+/g, "_")
      summaryRow[key] = user.totalHours > 0 ? user.totalHours.toFixed(1) : "0"
    })
    data.push(summaryRow)

    this.exportToCSV({
      sheetName: "Matriz_Horas_Diarias_INVOKE",
      columns,
      data,
      includeMetadata: true,
    })
  }
}
